# Generated by Django 5.1.1 on 2024-11-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(max_length=255, upload_to='enhanced_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(max_length=255, upload_to='videos/')),
            ],
        ),
    ]
