# Generated by Django 5.1.1 on 2024-11-08 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reducer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancedvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originalvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enhancedvideo',
            name='original_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_videos', to='reducer.originalvideo'),
        ),
    ]
